imports:
    - { resource: parameters.yml }
    - { resource: parameters/parameters.dir.yml }
    - { resource: parameters/parameters.request.yml }
    - { resource: parameters/parameters.log.yml }
    - { resource: parameters/parameters.vk.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"

monolog:
    handlers:
        consumer_collect:
            type:     rotating_file
            path:     '%kernel.logs_dir%/consumer-collect.log'
            level:    '%log.consumer_collect.level%'
            channels: ['consumer_collect']
            max_files: 7

        consumer_parse:
            type:     rotating_file
            path:     '%kernel.logs_dir%/consumer-parse.log'
            level:    '%log.consumer_parse.level%'
            channels: ['consumer_parse']
            max_files: 7

        consumer_publish:
            type:     rotating_file
            path:     '%kernel.logs_dir%/consumer-publish.log'
            level:    '%log.consumer_publish.level%'
            channels: ['consumer_publish']
            max_files: 7

        consumer_notify:
            type:     rotating_file
            path:     '%kernel.logs_dir%/consumer-notify.log'
            level:    '%log.consumer_notify.level%'
            channels: ['consumer_notify']
            max_files: 7

    channels:
       - "consumer_collect"
       - "consumer_parse"
       - "consumer_publish"
       - "consumer_notify"
